services:
  stt-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: realtime-stt-server-gpu
    ports:
      - "8011:8011"  # Control WebSocket port
      - "8012:8012"  # Data WebSocket port
    env_file:
      - .env
    environment:
      # - NVIDIA_VISIBLE_DEVICES=all
      # - CUDA_VISIBLE_DEVICES=0
      - TORCH_HOME=/app/models
      - HF_HOME=/app/cache
      - TRANSFORMERS_CACHE=/app/cache
      - PYTHONUNBUFFERED=1
    volumes:
      # Монтируем директорию для моделей (чтобы не скачивать каждый раз)
      - ./models:/app/models
      # Монтируем директорию для кеша HuggingFace и других моделей
      - ./cache:/app/cache
      # Монтируем директорию для логов
      - ./logs:/app/logs
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import socket; s = socket.socket(); s.settimeout(5); result = s.connect_ex(('localhost', 8011)); s.close(); exit(0 if result == 0 else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s  # Увеличен для загрузки CUDA моделей

# Опциональный сервис для мониторинга
  # portainer:
  #   image: portainer/portainer-ce:latest
  #   container_name: portainer
  #   restart: unless-stopped
  #   security_opt:
  #     - no-new-privileges:true
  #   volumes:
  #     - /etc/localtime:/etc/localtime:ro
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - ./portainer-data:/data
  #   ports:
  #     - 9000:9000

networks:
  default:
    name: stt-network